name: yeras_ai
description: "Free offline AI on your phone"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.3.2
  shared_preferences: ^2.5.5
  device_info_plus: ^13.2.0
  llamadart: ^0.9.0
  path_provider: ^2.1.6
  path: ^1.9.1
  flutter_markdown_plus: ^1.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/data/models_catalog.json
